### ISSUE TITLE
Correção da renderização ao responder uma mensagem

### ISSUE THREAD

**Issue by ettobr** [dollyzn/whaticket-cero#1]
Ao responder uma mensagem, a imagem não aparece junto com o texto, essa solução já existe no link https://github.com/rtenorioh/Press-Ticket/commit/6e68ec866104a11f90f52ae9d635899f186a1bab , poderia atualizar para Cero.

**Comment by dollyzn** [comment]
Olá! Obrigado pela observação, utilizei as modificações do rtenorioh e ainda adicionei um span para as imagens com legenda

**Comment by ettobr** [comment]
Legal! valeu!!!, seu repositório está mto bom, sem bugs, isso é excelente! outra observação se puder adicionar, se for interessante, é o histórico das conversas dentro dos tickets, trabalho com gráfica, e ter o histórico das conversas em tickets novos seria mto bom...

**Comment by dollyzn** [comment]
> Legal! valeu!!!, seu repositório está mto bom, sem bugs, isso é excelente! outra observação se puder adicionar, se for interessante, é o histórico das conversas dentro dos tickets, trabalho com gráfica, e ter o histórico das conversas em tickets novos seria mto bom...

Vou estudar a possibilidade de criar o histórico para ser mostrado dentro de um modal e não ser mostrado dentro do ticket, o repositório tinha essa função mas percebi que tinha alguns bugs, por exemplo, se uma pessoa tivesse o ticket em uma conexão e mandasse mensagem para outra, por conta do histórico ativo o ticket já aberto com a primeira conexão recebia também todas as mensagens do novo ticket, mas no geral é uma funcionalidade interessante
