### ISSUE TITLE
Whaticket Notification Bug

### ISSUE THREAD

**Issue by codsec** [dollyzn/whaticket-cero#2]
No whaticket do canove, existe um bug na notificação no qual ela aparece para todos os usuarios, vc corrigiu isso?(existe um fix para isso tambem no github do canove e no pressticket tbm porem é um gambiarra e não funciona mt bem pois ele corrige o problema na webinterface porem as notificações do windows ainda aparecem para todos) você tem essa correção na sua versão?

**Comment by dollyzn** [comment]
boa tarde, como na empresa as pessoas que utilizam a aplicação sempre desabilitam a notificação do windows eu nao cheguei a estudar esse bug, dando uma olhada verifiquei que as notificações de tickets com fila em que o usuario nao tem acesso estao sendo recebidas sim, tendo em vista isso fiz uma pequena possivel solução para esse seu problema que irei publicar no proximo commit

**Comment by codsec** [comment]
> boa tarde, como na empresa as pessoas que utilizam a aplicação sempre desabilitam a notificação do windows eu nao cheguei a estudar esse bug, dando uma olhada verifiquei que as notificações de tickets com fila em que o usuario nao tem acesso estao sendo recebidas sim, tendo em vista isso fiz uma pequena possivel solução para esse seu problema que irei publicar no proximo commit

vlw ficarei no aguardo

**Comment by codsec** [comment]
> a alteração é apenas no frontend e bem simples, da uma olhada e me confirma se era realmente isso

Deve funcionar sim, estarei fazendo uns testes, o problema em si tbm parece ter sido resolvido com isso;
`|| user.queues.map(q => q.id).indexOf(data.ticket.queueId) === -1;`
![image](https://user-images.githubusercontent.com/44205014/220996523-3e7ac65a-5562-41f6-b249-cf379e4fb230.png)

**Comment by dollyzn** [comment]
> Deve funcionar sim, estarei fazendo uns testes, o problema em si tbm parece ter sido resolvido com isso; `|| user.queues.map(q => q.id).indexOf(data.ticket.queueId) === -1;` ![image](https://user-images.githubusercontent.com/44205014/220996523-3e7ac65a-5562-41f6-b249-cf379e4fb230.png)

ok, essa solução tbm é possivel, as duas formas entregam o mesmo resultado
