### ISSUE TITLE
Login não avança

### ISSUE THREAD

**Issue by mxyzt** [dollyzn/whaticket-cero#4]
Olá amigo, em primeiro lugar o seu trabalho é excelente. Segui todos os passos, mas quando chego na página de login fica "carregando" e não faz nada. Já tentei reiniciar o nginx e fazer "pm2 restart all" e nada

**Comment by dollyzn** [comment]
Boa noite! agradeço pelo elogio, esse trabalho só foi possivel graças a comunidade

agora sobre o erro, abra as ferramentas de desenvolvedor e tira um print do console para eu conseguir entender oque esta acontecendo por favor

**Comment by mxyzt** [comment]
> ¡Buenas noches! agradeço pelo elogio, esse trabalho só foi possivel graças a comunidade
> 
> agora sobre o erro, abra as ferramentas de desenvolvedor e tira um print do console para eu conseguir entender oque esta acontecendo por favor

Muito obrigado por responder. Desculpe minha ignorância, sou novo no assunto, como faço para acessar as ferramentas do desenvolvedor? Estou usando o Google Cloud Platform. O endereço do front-end é https://wa.infoya.ga e o back-end é https:waapi.infoya.ga.

Quando tento fazer o login, a página fica carregando e não entra

**Comment by dollyzn** [comment]
inclusive, essa versão tem algumas peculiaridades da Cero, que é uma clinica de radiologia, como a mensagem de saudação que esta sendo enviada com botões (descontinuado), sendo assim caso vc queira utilizar recomendo que remova os recursos no quais não se enquadram no seu uso

**Comment by mxyzt** [comment]
> > > ¡Buenas noches! agradeço pelo elogio, esse trabalho só foi possivel graças a comunidade
> > > agora sobre o erro, abra as ferramentas de desenvolvedor e tira um print do console para eu conseguir entender oque esta acontecendo por favor
> > 
> > 
> > Muito obrigado por responder. Desculpe minha ignorância, sou novo no assunto, como faço para acessar as ferramentas do desenvolvedor? Estou usando o Google Cloud Platform. O endereço do front-end é https://wa.infoya.ga e o back-end é https://waapi.infoya.ga.
> > Quando tento fazer o login, a página fica carregando e não entra ![IGJOYrbiET](https://user-images.githubusercontent.com/130943477/239580067-e773ccba-8a52-44b8-bfda-fe9a00901a28.png)
> 
> dei uma olhada e acredito que o erro esteja no seu arquivo .env, verifica nos dois arquivos, o do frontend e o backend, se todas as urls estão com o `https://` no começo e não `http://`

Perfeito, vou verificar isso, embora lembre que coloquei tudo como está no tutorial. As portas devem ser 443 e 8080 certo?

**Comment by mxyzt** [comment]
> inclusive, essa versão tem algumas peculiaridades da Cero, que é uma clinica de radiologia, como a mensagem de saudação que esta sendo enviada com botões (descontinuado), sendo assim caso vc queira utilizar recomendo que remova os recursos no quais não se enquadram no 
![chrome_J0cKZJrYEk](https://github.com/dollyzn/whaticket-cero/assets/130943477/fef8c9e8-9e8c-41f8-afd5-578593ed1def)
seu uso

Agora recebo a mensagem em vermelho: =(

**Comment by mxyzt** [comment]
consegui resolver! Funciona de 10! muito obrigado!!

**Comment by dollyzn** [comment]
perfeito, qualquer dúvida pode me contatar novamente
