### ISSUE TITLE
Error sequelize db:migrate

### ISSUE THREAD

**Issue by brilyanilhamsadewo** [dollyzn/whaticket-cero#7]
when I try to run `$ npx sequelize db:migrate`

Sequelize CLI [Node: 16.15.0, CLI: 5.5.1, ORM: 5.22.5]

ERROR: Error reading "dist/config/database.js". Error: SyntaxError: Unexpected token ':'

I am using Amazon Linux 2 instead of Ubuntu because I already have an instance with Puppeteer installed. Is it because I use a different OS that causes this, or is there anything I missed?

**Comment by dollyzn** [comment]
I don't think this is due to your OS, apparently it's something in the file, build, or even a lack of defined parameters in the .env. How is your .env file?

**Comment by brilyanilhamsadewo** [comment]
> I don't think this is due to your OS, apparently it's something in the file, build, or even a lack of defined parameters in the .env. How is your .env file?

```
NODE_ENV=DEVELOPMENT
BACKEND_URL=https://backend.domain.com
FRONTEND_URL=https://ticket.domain.com
PROXY_PORT=443
PORT=8080

DB_HOST=localhost
DB_DIALECT=mysql
DB_USER=
DB_PASS=
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756
```
 I am also using MariaDB as a database server

**Comment by dollyzn** [comment]
you need to define the `DB_USER`, `DB_PASS`, and as your DB is MariaDB, set the `DB_DIALECT` to `mariadb`.
